### ISSUE TITLE
Reduction recipe

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/imageredux#10]
As written by Richard on the board today:
(I changed the averages to median stack)

1. Median-stack Darks --> MD (Master Dark)
2. Median-stack flats --> AF
3. Normalize AF --> FF (Flat Field)
4. Subtract MD from OBJ --> OBJ'
5. Subtract MD from FF --> MF (Master Flat)
6. OBJ' divided by MF --> Calibrated frame

Questions, suggestions?

**Comment by rcamuccio** [comment]
Currently the routine is the following:

1. Median combine darks --> MD
2. Median combine flats --> AF
3. Subtract MD from AF --> MF
4. Optional: User can choose to normalize MF by median --> MF
5. Subtract MD from OBJ --> OBJ-MIN-DARK
6. Subtract MF from OBJ-MIN-DARK --> CAL-OBJ

This seems to work.

**Comment by rcamuccio** [comment]
Closing this unless we run into issues with reduction down the line.
