### ISSUE TITLE
master flat creation

### ISSUE THREAD

**Issue by laralds** [toros-astro/imageredux#11]
On the current script for creating the master flat it seems that the steps are not in a correct order.

According to what I understand, it should be:
- subtract master dark from each of the flats
- combine the (flat-dark) to create the master flat

This is what it's doing now:
- Combine the flats 
- subtract the master dark from the combined-flats to create a master flat.

**Comment by martinberoiz** [comment]
🤔 I think you may be right

**Comment by laralds** [comment]
Mathematically its it seems to be same.  Yes Martin, I re-checked and you were correct

**Comment by juanlg7** [comment]
So is it the same to subtract the darkmaster from the masterflat than to subtract the darkmaster from the flats, then combine the flats-darkmaster?

**Comment by martinberoiz** [comment]
What about those tests you ran that were different? If you think it's not an issue you can go on and close this issue.

**Comment by martinberoiz** [comment]
@juanlg7 Mathematically, with the average it's the same:

1/N sum_i (F_i - D) = (1/N sum_i F_i) - D

but it's not clear if the median will be the same or not...

**Comment by rcamuccio** [comment]
Hi everybody. I think based on my little calculation (and also your previous math @martinberoiz) I think these routines are identical.

At this point, we just need to add normalizing the flats to the code and the master flat portion should be finished.

**Comment by martinberoiz** [comment]
@laralds had code for normalizing that was trying to push

**Comment by rcamuccio** [comment]
@laralds did a fantastic job. This issue is closed.
