### ISSUE TITLE
moving some code into __main__ section

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/imageredux#12]
Hello,
I was just looking at the code and I think this chunk:

    # Initialize lists
    dark_list = []
    flat_list = []
    object_list = []

    # Append calibration and object frames to list
    for frame in glob.glob("*.fit"):

        if "dark" in frame:
            dark_list.append(frame)
        elif "flat" in frame:
            flat_list.append(frame)
        else:
            object_list.append(frame)

should be in the `__main__` section. Basically so that it doesn't execute when the module is imported. It could be right after the argument parsing (that I just added) and before calling `main()`.

Opinions?

**Comment by martinberoiz** [comment]
well, actually I'm interested in @rcamuccio's opinion, since you wrote that part :)

**Comment by moemyself3** [comment]
I agree with @martinberoiz

These are global variables, but I think including them in the scope of main would still work as desired since the functions would be called from main (or am I not interpreting the use of variables in the scopes correctly?)

What say you @rcamuccio

**Comment by rcamuccio** [comment]
Hey @martinberoiz and @moemyself3 ... I just moved all of that into the main() function. The code is pushed now.
