### ISSUE TITLE
dark subtraction from object frames

### ISSUE THREAD

**Issue by rcamuccio** [toros-astro/imageredux#13]
I noticed that all the calibration frame prep routines seem to work (someone can potentially verify this). However, the code seems to do some weird stuff where we subtract the master dark from each object frame. At that point, the images return minimum pixel values in the negatives (a few negative thousand counts). I *think* this is the source of the error I was noticing earlier.

**Comment by martinberoiz** [comment]
could it be because of the different exposure times and scaling?

**Comment by rcamuccio** [comment]
I think I'll close this issue after extensive discussion on the subject (and testing).
