### ISSUE TITLE
Intrusive clear with -h --help

### ISSUE THREAD

**Issue by moemyself3** [toros-astro/imageredux#19]
When user runs:
`python imageredux.py --help`

The buffer is cleared! Not a big deal just unexpected.

**Comment by martinberoiz** [comment]
ah, yeah, I'm not very fond of the `clear()` tbh :p

**Comment by rcamuccio** [comment]
Ah, do you mean as in where we use this?

`   os.system('clear') `
`    print() `
`    print("// ImageRedux") `
`    print("// CGWA TDAG - Aug 2017") `
`    print() `

**Comment by moemyself3** [comment]
@rcamuccio Yes lol

@martinberoiz usually in the terminal when you type --help it show the help with everything you had in the buffer before.

Clear() moves everything beyond the top part of your screen so it clears what is seen on the buffer.

**Comment by moemyself3** [comment]
I think moving the block @rcamuccio wrote into the top part of main would solve this.

**Comment by martinberoiz** [comment]
Oh, I moved the intro block to `main()` in 5a1dc9267e1e292547fa40db830c66b7e2b9f390

Still works as before except when displaying help.
