### ISSUE TITLE
Reduce individual light frames

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/imageredux#4]
Something like

    def reduce_image(some input):
        # reduce image with the flat and dark
        # save to file?
        return image

input could be either FITS file name or the numpy array of the image, or a CCDProc data structure

**Comment by moemyself3** [comment]
I have created a function that will take three inputs, the science image (image), master_dark, and master_flat, which returns a reduced fits file ( image_redux.fits )

**Comment by martinberoiz** [comment]
Great! I'll write a test for it asap
